name: Github Secret
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  [workflow_dispatch] 
jobs:
    Test-secret:
      runs-on: ubuntu-latest
      steps:
        - name: downloading unzip
          run: sudo apt-get install -y unzip
        - uses: actions/checkout@v4
        - run: echo "${{ github.actor }} is going to access a secret"
        - run: unzip secret.zip -P ${{ secrets.UNZIP_PASS }} secret.zip
        - run: cat secret.txt